FROM archlinux:latest

RUN pacman -Sy --noconfirm --needed archlinux-keyring \
    && pacman -S --noconfirm --needed bash \
    && pacman -Scc --noconfirm

COPY bootstrap.sh /bootstrap.sh
RUN chmod +x /bootstrap.sh

CMD ["/bin/bash"]
