[window]
padding = { x = 0, y = 0 }
dynamic_padding = true

[font]
normal = { family = "Caskaydia Mono NF", style = "Regular" }
size = 12
offset = { x = 1, y = 5 }
glyph_offset = { x = 0, y = 2 }
builtin_box_drawing = true
